---
- hosts: all
  become: yes
  become_user: root
  vars:

  tasks:
   - apt_key: url=https://packages.icinga.com/icinga.key state=present

   - name: Install apt-transport-https
     apt: name=apt-transport-https state=latest

   - apt_repository: 
         repo: deb https://packages.icinga.com/ubuntu icinga-xenial main
         state: present 

   - name: Install icinga2 from apt repos
     apt: name={{ item }} state=latest
     with_items:
        - icinga2
        - monitoring-plugins
        - vim-icinga2
        - vim-addon-manager

   - name: Configuration syntax highlighting using vim
     command: /usr/bin/vim-addon-manager -w install icinga2


   - name: Install docker environment
     apt: name={{ item }} state=latest
     with_items:
        - docker.io
        - python-pip

   - pip:
      name: docker-py

   - name: Create MySql docker container
     docker:
         name: mysql
         image: mysql
         state: restarted

   - name: Create httpd docker container
     docker:
         name: httpd
         image: httpd
         state: restarted
   - name: Replacing httpd conf with original conf to handle log properly
     command: /usr/bin/docker exec httpd mv /usr/local/apache2/conf/original/httpd.conf /usr/local/apache2/conf/httpd.conf; docker restart httpd
   
   - name: Copy cron scripts to root home directory
     copy: src=./scripts/{{ item }} dest=/root/ mode="a+x"
     with_items:
        - upload_docker_logs.sh

   - name: Create cron job to send files to S3
     cron: name="copy logs to s3 bucket" minute="1" job="/root/upload_docker_logs.sh"
	
   - name: Installing PostgreSQL database server
	 cron: apt-get install postgresql

   - name: Installing the IDO modules for PostgreSQL
	 cron: apt-get install icinga2-ido-pgsql

   - name: Setting up the PostgreSQL database
	 command: cd /tmp; sudo -u postgres psql -c "CREATE ROLE icinga WITH LOGIN PASSWORD 'icinga'" ; sudo -u postgres createdb -O icinga -E UTF8 icinga ; sudo -u postgres createlang plpgsql icinga 
