---
- hosts: all
  become: yes
  become_user: root
  vars:

  tasks:
   - apt_key: url=https://packages.icinga.com/icinga.key state=present

   - name: Install apt-transport-https
     apt: name=apt-transport-https state=latest

   - apt_repository: 
         repo: deb https://packages.icinga.com/ubuntu icinga-xenial main
         state: present 

   - name: Install icinga2 from apt repos
     apt: name={{ item }} state=latest
     with_items:
        - icinga2
        - monitoring-plugins
        - vim-icinga2
        - vim-addon-manager

   - name: Configuration syntax highlighting using vim
     command: /usr/bin/vim-addon-manager -w install icinga2


   - name: Install docker environment
     apt: name={{ item }} state=latest
     with_items:
        - docker.io
        - python-pip

   - pip:
      name: docker-py

   - pip:
      name: psycopg2

   - name: Create MySql docker container
     docker:
         name: mysql
         image: mysql
         state: started
         env:
             MYSQL_ROOT_PASSWORD: silent

   - name: Copy apache2 conf to root home directory
     copy: src=./httpd-conf dest=/root/ 

   - name: Create httpd docker container
     docker:
         name: httpd
         image: httpd
         state: started
         volumes:
            /root/httpd-conf:/usr/local/apache2/conf
         ports:
            8080:80
  
   - name: Copy cron scripts to root home directory
     copy: src=./scripts/{{ item }} dest=/root/ mode="a+x"
     with_items:
        - upload_docker_logs.sh


   - name: Create cron job to send files to S3
     cron: name="copy logs to s3 bucket" minute="*" job="/root/upload_docker_logs.sh"
     #cron: name="copy logs to s3 bucket" hour="19" job="/root/upload_docker_logs.sh"

   - name: Installing icigna2 web
     apt: name={{ item }} state=latest
     with_items:
        - apache2
        - php-intl
        - icingaweb2
        - php-dom
        - php-imagick
        - php-pgsql
        - postgresql 
        - icinga2-ido-pgsql

   - lineinfile:
        dest: /etc/php/7.0/apache2/php.ini
        line: "date.timezone = Asia/Kolkata"


   - service:
        name: apache2
        state: restarted

#   - name: Create postgres role and users
#     command:  "psql -c \"CREATE ROLE icinga WITH LOGIN PASSWORD 'icinga'\""
#     become_user: postgres
#     ignore_errors: yes
#
#   - name: Create database
#     command: "sudo -u postgres createdb -O icinga -E UTF8 icinga"
#     become_user: postgres
#     ignore_errors: yes
#    
#   - name: adding icinga user to login using password    
#     blockinfile:
#        dest: /etc/postgresql/9.5/main/pg_hba.conf
#        insertafter: "# Put your actual configuration her"
#        content: |
#          local   icinga      icinga                            md5
#          host    icinga      icinga      127.0.0.1/32          md5
#          host    icinga      icinga      ::1/128               md5
#
#   - name: Import blank database
#     become_user: icinga
#     command: "psql icinga < /usr/share/icinga2-ido-pgsql/schema/pgsql.sql"
#
#   - name: enable feature
#     command: icinga2 feature enable ido-pgsql

